# Generated by Django 5.2 on 2025-05-19 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('tokenization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_type', models.CharField(choices=[('PLATFORM', 'Platform Governance'), ('ASSET', 'Asset Management'), ('TREASURY', 'Treasury Allocation'), ('UPGRADE', 'System Upgrade')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Voting Active'), ('PASSED', 'Proposal Passed'), ('REJECTED', 'Proposal Rejected'), ('IMPLEMENTED', 'Implemented')], default='DRAFT', max_length=12)),
                ('voting_system', models.CharField(choices=[('SIMPLE_MAJORITY', '50%+1'), ('SUPER_MAJORITY', '67%'), ('QUORUM', 'Quorum')], default='SIMPLE_MAJORITY', max_length=20)),
                ('start_block', models.PositiveBigIntegerField()),
                ('end_block', models.PositiveBigIntegerField()),
                ('min_tokens_to_pass', models.DecimalField(blank=True, decimal_places=18, max_digits=28, null=True)),
                ('execution_calls', models.JSONField()),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('execution_tx', models.CharField(blank=True, max_length=66)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.userprofile')),
                ('tokenized_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='tokenization.tokenizedasset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('ABSTAIN', 'Abstain')], max_length=7)),
                ('voting_power', models.DecimalField(decimal_places=18, max_digits=28)),
                ('voted_at_block', models.PositiveBigIntegerField()),
                ('signature', models.CharField(max_length=132)),
                ('is_delegated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delegate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_votes', to='core.userprofile')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.userprofile')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='governance.votingproposal')),
            ],
        ),
        migrations.CreateModel(
            name='GovernanceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('scope', models.CharField(choices=[('GLOBAL', 'Platform-wide'), ('ASSET', 'Per Asset'), ('USER', 'User-specific')], default='GLOBAL', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('condition', models.JSONField()),
                ('actions', models.JSONField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='governance.governancerule')),
                ('created_by_proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='governance.votingproposal')),
            ],
            options={
                'ordering': ['name', '-version'],
                'get_latest_by': 'version',
            },
        ),
        migrations.AddIndex(
            model_name='votingproposal',
            index=models.Index(fields=['tokenized_asset', 'status'], name='governance__tokeniz_c17e4f_idx'),
        ),
        migrations.AddIndex(
            model_name='votingproposal',
            index=models.Index(fields=['proposal_type', 'end_block'], name='governance__proposa_704a32_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['proposal', 'choice'], name='governance__proposa_0748ea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('proposal', 'voter')},
        ),
    ]
