# Generated by Django 5.2 on 2025-05-19 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('VALUATION', 'Property Valuation'), ('PREDICTIVE', 'Market Prediction'), ('RECOMMENDER', 'Investment Recommender'), ('RISK', 'Risk Assessment')], max_length=15)),
                ('version', models.CharField(max_length=50)),
                ('framework', models.CharField(choices=[('TENSORFLOW', 'TensorFlow'), ('PYTORCH', 'PyTorch'), ('SKLEARN', 'Scikit-learn'), ('XGBOOST', 'XGBoost')], max_length=10)),
                ('storage_path', models.CharField(max_length=255)),
                ('checksum', models.CharField(max_length=64)),
                ('is_production', models.BooleanField(default=False)),
                ('hyperparameters', models.JSONField()),
                ('metrics', models.JSONField()),
                ('deployed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['model_type', '-deployed_at'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.JSONField()),
                ('output_data', models.JSONField()),
                ('interpreted_result', models.TextField()),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prediction_time', models.DecimalField(decimal_places=4, max_digits=10)),
                ('batch_id', models.CharField(blank=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('data_type', models.CharField(choices=[('STRUCTURED', 'Structured Data'), ('IMAGES', 'Image Data'), ('TEXT', 'Natural Language'), ('TIME_SERIES', 'Time Series')], max_length=15)),
                ('version', models.CharField(max_length=50)),
                ('storage_location', models.CharField(max_length=255)),
                ('size_gb', models.DecimalField(decimal_places=2, max_digits=10)),
                ('record_count', models.PositiveIntegerField()),
                ('date_range_start', models.DateField()),
                ('date_range_end', models.DateField()),
                ('geographic_scope', models.JSONField()),
                ('data_schema', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Training Data',
            },
        ),
        migrations.CreateModel(
            name='FeatureSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('features', models.JSONField()),
                ('transformations', models.JSONField()),
                ('feature_importance', models.JSONField(blank=True, null=True)),
                ('correlation_matrix', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_integration.featureset')),
            ],
        ),
    ]
