# Generated by Django 5.2 on 2025-05-19 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_integration', '0001_initial'),
        ('markets_valuation', '0001_initial'),
        ('property', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='modelversion',
            name='deployed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='feature_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ai_integration.featureset'),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='parent_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_integration.modelversion'),
        ),
        migrations.AddField(
            model_name='prediction',
            name='market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='markets_valuation.markettrend'),
        ),
        migrations.AddField(
            model_name='prediction',
            name='model_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ai_integration.modelversion'),
        ),
        migrations.AddField(
            model_name='prediction',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.property'),
        ),
        migrations.AddField(
            model_name='trainingdata',
            name='parent_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_integration.trainingdata'),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='training_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ai_integration.trainingdata'),
        ),
        migrations.AddField(
            model_name='featureset',
            name='required_data',
            field=models.ManyToManyField(to='ai_integration.trainingdata'),
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(fields=['model_version', 'created_at'], name='ai_integrat_model_v_2e5581_idx'),
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(fields=['property', 'model_version'], name='ai_integrat_propert_70897e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trainingdata',
            unique_together={('name', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='modelversion',
            unique_together={('model_type', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='featureset',
            unique_together={('name', 'version')},
        ),
    ]
