# Generated by Django 5.2 on 2025-05-19 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('tokenization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_type', models.CharField(choices=[('DIRECT', 'Direct Purchase'), ('FRACTIONAL', 'Fractional Ownership'), ('FUND', 'Investment Fund')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('token_amount', models.DecimalField(decimal_places=18, max_digits=28)),
                ('entry_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('LIQUIDATED', 'Liquidated'), ('DEFAULTED', 'Defaulted')], default='PENDING', max_length=10)),
                ('investment_date', models.DateTimeField(auto_now_add=True)),
                ('exit_date', models.DateTimeField(blank=True, null=True)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('contract_hash', models.CharField(blank=True, max_length=66)),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investments', to='tokenization.tokenizedasset')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investments', to='core.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('INVESTMENT', 'Investment'), ('DIVIDEND', 'Dividend'), ('WITHDRAWAL', 'Withdrawal'), ('TOKEN_TRANSFER', 'Token Transfer'), ('ESCROW', 'Escrow Settlement')], max_length=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], default='PENDING', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('blockchain_tx_hash', models.CharField(blank=True, max_length=66)),
                ('blockchain_network', models.CharField(blank=True, max_length=20)),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transactions', to='core.userprofile')),
                ('related_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tokenization.tokenizedasset')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transactions', to='core.userprofile')),
            ],
            options={
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='Escrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escrow_type', models.CharField(choices=[('PURCHASE', 'Property Purchase'), ('DIVIDEND', 'Dividend Distribution'), ('DISPUTE', 'Dispute Resolution')], max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RELEASED', 'Released'), ('REFUNDED', 'Refunded'), ('DISPUTED', 'In Dispute')], default='ACTIVE', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('release_conditions', models.TextField()),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('smart_contract_address', models.CharField(blank=True, max_length=42)),
                ('beneficiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='escrow_benefits', to='core.userprofile')),
                ('depositor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escrow_deposits', to='core.userprofile')),
                ('related_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='DividendPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('token_amount', models.DecimalField(blank=True, decimal_places=18, max_digits=28, null=True)),
                ('payout_date', models.DateTimeField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('is_reinvested', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tokenization.tokenizedasset')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dividends', to='transactions.investment')),
                ('blockchain_tx', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.transaction')),
            ],
            options={
                'ordering': ['-payout_date'],
            },
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['investor', 'status'], name='transaction_investo_f28327_idx'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['asset', 'investment_date'], name='transaction_asset_i_f7094e_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['from_user', 'status'], name='transaction_from_us_cf4309_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['to_user', 'transaction_type'], name='transaction_to_user_fb508b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dividendpayout',
            unique_together={('investment', 'period_start', 'period_end')},
        ),
    ]
