# Generated by Django 5.2 on 2025-05-19 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=42, unique=True)),
                ('wallet_type', models.CharField(choices=[('EOA', 'Externally Owned Account'), ('CONTRACT', 'Smart Contract Wallet')], max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('is_hardware', models.BooleanField(default=False)),
                ('last_backup', models.DateTimeField(blank=True, null=True)),
                ('network', models.CharField(default='Ethereum', max_length=20)),
                ('derivation_path', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('blockchain', models.CharField(blank=True, max_length=15, null=True)),
                ('wallet_address', models.CharField(blank=True, max_length=42, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('INVESTOR', 'Investor'), ('PROPERTY_OWNER', 'Property Owner'), ('ADMIN', 'Admin')], max_length=15)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('profile_image', models.ImageField(blank=True, upload_to='profile_images/')),
                ('bio', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_level', models.PositiveSmallIntegerField(default=0)),
                ('preferred_currency', models.CharField(default='USD', max_length=3)),
                ('language', models.CharField(default='en', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('default_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.blockchainwallet')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KYCVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_legal_name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('tax_id', models.CharField(blank=True, max_length=50)),
                ('id_type', models.CharField(max_length=20)),
                ('id_number', models.CharField(max_length=50)),
                ('id_front', models.FileField(upload_to='kyc_documents/')),
                ('id_back', models.FileField(blank=True, upload_to='kyc_documents/')),
                ('selfie', models.ImageField(upload_to='kyc_selfies/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Verified'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('verification_hash', models.CharField(blank=True, max_length=66)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to='core.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='InvestorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_tolerance', models.CharField(choices=[('LOW', 'Low Risk'), ('MODERATE', 'Moderate'), ('HIGH', 'High Risk')], max_length=10)),
                ('investment_goals', models.TextField(blank=True)),
                ('target_countries', models.JSONField(default=list)),
                ('target_cities', models.JSONField(default=list)),
                ('min_investment', models.DecimalField(decimal_places=2, default=1000, max_digits=12)),
                ('max_investment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('target_roi', models.DecimalField(decimal_places=2, max_digits=5)),
                ('preferred_hold_period', models.PositiveSmallIntegerField(default=24, help_text='Preferred investment duration in months')),
                ('requires_secondary_market', models.BooleanField(default=True)),
                ('wants_dividend_reinvestment', models.BooleanField(default=False)),
                ('alert_on_new_properties', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('preferred_property_types', models.ManyToManyField(blank=True, to='property.propertytype')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investor_profile', to='core.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='blockchainwallet',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='core.userprofile'),
        ),
        migrations.CreateModel(
            name='Web3Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=42)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(fields=('wallet_address', 'blockchain', 'email'), name='unique_blockchain_wallet_address_email'),
        ),
        migrations.AlterUniqueTogether(
            name='blockchainwallet',
            unique_together={('user_profile', 'address')},
        ),
        migrations.AlterUniqueTogether(
            name='web3session',
            unique_together={('user', 'session_key')},
        ),
    ]
