# Generated by Django 5.2 on 2025-05-19 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenizedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_standard', models.CharField(choices=[('ERC20', 'Fungible Token'), ('ERC721', 'Non-Fungible Token'), ('ERC1400', 'Security Token')], max_length=10)),
                ('token_symbol', models.CharField(max_length=5)),
                ('token_name', models.CharField(max_length=100)),
                ('total_supply', models.DecimalField(decimal_places=18, max_digits=28)),
                ('initial_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('contract_address', models.CharField(max_length=42)),
                ('deployer_address', models.CharField(max_length=42)),
                ('deployment_tx_hash', models.CharField(max_length=66)),
                ('deployment_block', models.PositiveBigIntegerField()),
                ('is_tradable', models.BooleanField(default=False)),
                ('dividend_period', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly')], default='QUARTERLY', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tokenized_asset', to='property.property')),
            ],
        ),
        migrations.CreateModel(
            name='TokenOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=18, max_digits=28)),
                ('locked_balance', models.DecimalField(decimal_places=18, default=0, max_digits=28)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('last_sync_block', models.PositiveBigIntegerField()),
                ('wallet_address', models.CharField(max_length=42)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_records', to='tokenization.tokenizedasset')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_holdings', to='core.userprofile')),
            ],
            options={
                'unique_together': {('owner', 'asset')},
            },
        ),
        migrations.CreateModel(
            name='FractionalOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_percentage', models.DecimalField(decimal_places=4, max_digits=7)),
                ('acquisition_date', models.DateTimeField()),
                ('acquisition_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('voting_power', models.DecimalField(decimal_places=4, max_digits=7)),
                ('has_voting_rights', models.BooleanField(default=True)),
                ('ownership_agreement', models.FileField(upload_to='ownership_agreements/')),
                ('agreement_hash', models.CharField(max_length=64)),
                ('token_ownership', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fractional_details', to='tokenization.tokenownership')),
            ],
        ),
        migrations.CreateModel(
            name='TokenTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(max_length=66, unique=True)),
                ('tx_type', models.CharField(choices=[('MINT', 'Token Minting'), ('TRANSFER', 'Peer Transfer'), ('DIVIDEND', 'Dividend Payment'), ('BURN', 'Token Burn'), ('SWAP', 'Exchange Trade')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('block_number', models.PositiveBigIntegerField()),
                ('timestamp', models.DateTimeField()),
                ('from_address', models.CharField(blank=True, max_length=42, null=True)),
                ('to_address', models.CharField(blank=True, max_length=42, null=True)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=28)),
                ('gas_used', models.DecimalField(decimal_places=0, max_digits=12)),
                ('gas_price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('input_data', models.TextField(blank=True, null=True)),
                ('event_logs', models.JSONField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='tokenization.tokenizedasset')),
            ],
            options={
                'ordering': ['-block_number'],
                'indexes': [models.Index(fields=['tx_hash'], name='tokenizatio_tx_hash_818a06_idx'), models.Index(fields=['from_address'], name='tokenizatio_from_ad_02df48_idx'), models.Index(fields=['to_address'], name='tokenizatio_to_addr_f6d01c_idx'), models.Index(fields=['block_number'], name='tokenizatio_block_n_3046ac_idx')],
            },
        ),
    ]
