# Generated by Django 5.2 on 2025-05-19 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('BUILDING', 'Building Amenity'), ('UNIT', 'Unit Amenity'), ('COMMUNITY', 'Community Amenity')], max_length=20)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_standard', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial'), ('INDUSTRIAL', 'Industrial'), ('LAND', 'Land')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('reference_id', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('total_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usable_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_floors', models.PositiveIntegerField()),
                ('floor_number', models.PositiveIntegerField()),
                ('plot_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bedrooms', models.PositiveIntegerField()),
                ('bathrooms', models.PositiveIntegerField()),
                ('year_built', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('base_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('price_per_sqm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rental_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('current_rent', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('SOLD', 'Sold'), ('MAINTENANCE', 'Under Maintenance')], default='DRAFT', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(blank=True, to='property.amenity')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='property.propertytype')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('DEED', 'Title Deed'), ('BLUEPRINT', 'Blueprint'), ('SURVEY', 'Survey Report'), ('PERMIT', 'Building Permit'), ('CERTIFICATE', 'Occupancy Certificate'), ('CONTRACT', 'Sales Contract'), ('OTHER', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='property_documents/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='property.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('image_type', models.CharField(choices=[('MAIN', 'Main Image'), ('FLOOR_PLAN', 'Floor Plan'), ('INTERIOR', 'Interior View'), ('EXTERIOR', 'Exterior View'), ('AERIAL', 'Aerial View')], default='INTERIOR', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='property.property')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
