# Generated by Django 5.2 on 2025-05-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='floor_number',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='plot_size',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='total_area',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='total_floors',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='usable_area',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
