# Generated by Django 5.2 on 2025-06-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_property_floor_number_alter_property_plot_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='blockchain_tx_hash',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
    ]
