# Generated by Django 5.2 on 2025-06-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_property_blockchain_tx_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_available_for_rent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='purchase_type',
            field=models.CharField(blank=True, choices=[('SINGLE', 'single'), ('CROWDFUND', 'crowdfund')], default='SINGLE', max_length=20, null=True),
        ),
    ]
