# Generated by Django 5.2 on 2025-06-03 16:24

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_property_is_available_for_rent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='owners',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='property',
            name='purchase_type',
            field=models.CharField(blank=True, choices=[('SINGLE', 'single'), ('CROWDFUND', 'crowdfund'), ('ANY', 'any')], default='ANY', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='reference_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
