# Generated by Django 5.2 on 2025-06-04 09:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_property_owners_alter_property_purchase_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='reference_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False),
        ),
    ]
