# Generated by Django 5.2 on 2025-06-04 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_alter_property_reference_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='reference_id',
        ),
    ]
