# Generated by Django 5.2 on 2025-06-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_remove_property_reference_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='reference_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
