# Generated by Django 5.2 on 2025-06-04 09:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_property_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='reference_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False),
        ),
    ]
