# Generated by Django 5.2 on 2025-06-04 09:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_alter_property_reference_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='owners',
            field=models.ManyToManyField(related_name='properties', to=settings.AUTH_USER_MODEL),
        ),
    ]
